# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stole/monkey

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stole/monkey

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\" \"doc\" \"examples\" \"pkgconfig\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stole/monkey/CMakeFiles /home/stole/monkey//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stole/monkey/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named monkey

# Build rule for target.
monkey: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monkey
.PHONY : monkey

# fast build rule for target.
monkey/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monkey.dir/build.make CMakeFiles/monkey.dir/build
.PHONY : monkey/fast

#=============================================================================
# Target rules for targets named travis_doc

# Build rule for target.
travis_doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 travis_doc
.PHONY : travis_doc

# fast build rule for target.
travis_doc/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/travis_doc.dir/build.make libs/rapidjson/CMakeFiles/travis_doc.dir/build
.PHONY : travis_doc/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/Experimental.dir/build.make libs/rapidjson/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/Nightly.dir/build.make libs/rapidjson/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/Continuous.dir/build.make libs/rapidjson/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyMemoryCheck.dir/build.make libs/rapidjson/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyStart.dir/build.make libs/rapidjson/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyUpdate.dir/build.make libs/rapidjson/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyConfigure.dir/build.make libs/rapidjson/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyBuild.dir/build.make libs/rapidjson/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyTest.dir/build.make libs/rapidjson/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyCoverage.dir/build.make libs/rapidjson/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlyMemCheck.dir/build.make libs/rapidjson/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/NightlySubmit.dir/build.make libs/rapidjson/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalStart.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalUpdate.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalConfigure.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalBuild.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalTest.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalCoverage.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalMemCheck.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ExperimentalSubmit.dir/build.make libs/rapidjson/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousStart.dir/build.make libs/rapidjson/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousUpdate.dir/build.make libs/rapidjson/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousConfigure.dir/build.make libs/rapidjson/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousBuild.dir/build.make libs/rapidjson/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousTest.dir/build.make libs/rapidjson/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousCoverage.dir/build.make libs/rapidjson/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousMemCheck.dir/build.make libs/rapidjson/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/CMakeFiles/ContinuousSubmit.dir/build.make libs/rapidjson/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/doc/CMakeFiles/doc.dir/build.make libs/rapidjson/doc/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named archivertest

# Build rule for target.
archivertest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archivertest
.PHONY : archivertest

# fast build rule for target.
archivertest/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/archivertest.dir/build.make libs/rapidjson/example/CMakeFiles/archivertest.dir/build
.PHONY : archivertest/fast

#=============================================================================
# Target rules for targets named capitalize

# Build rule for target.
capitalize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 capitalize
.PHONY : capitalize

# fast build rule for target.
capitalize/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/capitalize.dir/build.make libs/rapidjson/example/CMakeFiles/capitalize.dir/build
.PHONY : capitalize/fast

#=============================================================================
# Target rules for targets named condense

# Build rule for target.
condense: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 condense
.PHONY : condense

# fast build rule for target.
condense/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/condense.dir/build.make libs/rapidjson/example/CMakeFiles/condense.dir/build
.PHONY : condense/fast

#=============================================================================
# Target rules for targets named filterkey

# Build rule for target.
filterkey: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filterkey
.PHONY : filterkey

# fast build rule for target.
filterkey/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/filterkey.dir/build.make libs/rapidjson/example/CMakeFiles/filterkey.dir/build
.PHONY : filterkey/fast

#=============================================================================
# Target rules for targets named filterkeydom

# Build rule for target.
filterkeydom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filterkeydom
.PHONY : filterkeydom

# fast build rule for target.
filterkeydom/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/filterkeydom.dir/build.make libs/rapidjson/example/CMakeFiles/filterkeydom.dir/build
.PHONY : filterkeydom/fast

#=============================================================================
# Target rules for targets named jsonx

# Build rule for target.
jsonx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jsonx
.PHONY : jsonx

# fast build rule for target.
jsonx/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/jsonx.dir/build.make libs/rapidjson/example/CMakeFiles/jsonx.dir/build
.PHONY : jsonx/fast

#=============================================================================
# Target rules for targets named lookaheadparser

# Build rule for target.
lookaheadparser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lookaheadparser
.PHONY : lookaheadparser

# fast build rule for target.
lookaheadparser/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/lookaheadparser.dir/build.make libs/rapidjson/example/CMakeFiles/lookaheadparser.dir/build
.PHONY : lookaheadparser/fast

#=============================================================================
# Target rules for targets named messagereader

# Build rule for target.
messagereader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 messagereader
.PHONY : messagereader

# fast build rule for target.
messagereader/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/messagereader.dir/build.make libs/rapidjson/example/CMakeFiles/messagereader.dir/build
.PHONY : messagereader/fast

#=============================================================================
# Target rules for targets named parsebyparts

# Build rule for target.
parsebyparts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parsebyparts
.PHONY : parsebyparts

# fast build rule for target.
parsebyparts/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/parsebyparts.dir/build.make libs/rapidjson/example/CMakeFiles/parsebyparts.dir/build
.PHONY : parsebyparts/fast

#=============================================================================
# Target rules for targets named pretty

# Build rule for target.
pretty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pretty
.PHONY : pretty

# fast build rule for target.
pretty/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/pretty.dir/build.make libs/rapidjson/example/CMakeFiles/pretty.dir/build
.PHONY : pretty/fast

#=============================================================================
# Target rules for targets named prettyauto

# Build rule for target.
prettyauto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 prettyauto
.PHONY : prettyauto

# fast build rule for target.
prettyauto/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/prettyauto.dir/build.make libs/rapidjson/example/CMakeFiles/prettyauto.dir/build
.PHONY : prettyauto/fast

#=============================================================================
# Target rules for targets named schemavalidator

# Build rule for target.
schemavalidator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 schemavalidator
.PHONY : schemavalidator

# fast build rule for target.
schemavalidator/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/schemavalidator.dir/build.make libs/rapidjson/example/CMakeFiles/schemavalidator.dir/build
.PHONY : schemavalidator/fast

#=============================================================================
# Target rules for targets named serialize

# Build rule for target.
serialize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serialize
.PHONY : serialize

# fast build rule for target.
serialize/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/serialize.dir/build.make libs/rapidjson/example/CMakeFiles/serialize.dir/build
.PHONY : serialize/fast

#=============================================================================
# Target rules for targets named simpledom

# Build rule for target.
simpledom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simpledom
.PHONY : simpledom

# fast build rule for target.
simpledom/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/simpledom.dir/build.make libs/rapidjson/example/CMakeFiles/simpledom.dir/build
.PHONY : simpledom/fast

#=============================================================================
# Target rules for targets named simplereader

# Build rule for target.
simplereader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simplereader
.PHONY : simplereader

# fast build rule for target.
simplereader/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/simplereader.dir/build.make libs/rapidjson/example/CMakeFiles/simplereader.dir/build
.PHONY : simplereader/fast

#=============================================================================
# Target rules for targets named simplepullreader

# Build rule for target.
simplepullreader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simplepullreader
.PHONY : simplepullreader

# fast build rule for target.
simplepullreader/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/simplepullreader.dir/build.make libs/rapidjson/example/CMakeFiles/simplepullreader.dir/build
.PHONY : simplepullreader/fast

#=============================================================================
# Target rules for targets named simplewriter

# Build rule for target.
simplewriter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simplewriter
.PHONY : simplewriter

# fast build rule for target.
simplewriter/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/simplewriter.dir/build.make libs/rapidjson/example/CMakeFiles/simplewriter.dir/build
.PHONY : simplewriter/fast

#=============================================================================
# Target rules for targets named sortkeys

# Build rule for target.
sortkeys: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sortkeys
.PHONY : sortkeys

# fast build rule for target.
sortkeys/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/sortkeys.dir/build.make libs/rapidjson/example/CMakeFiles/sortkeys.dir/build
.PHONY : sortkeys/fast

#=============================================================================
# Target rules for targets named tutorial

# Build rule for target.
tutorial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tutorial
.PHONY : tutorial

# fast build rule for target.
tutorial/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/tutorial.dir/build.make libs/rapidjson/example/CMakeFiles/tutorial.dir/build
.PHONY : tutorial/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) $(MAKESILENT) -f libs/rapidjson/example/CMakeFiles/examples.dir/build.make libs/rapidjson/example/CMakeFiles/examples.dir/build
.PHONY : examples/fast

src/monkey.o: src/monkey.cc.o
.PHONY : src/monkey.o

# target to build an object file
src/monkey.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monkey.dir/build.make CMakeFiles/monkey.dir/src/monkey.cc.o
.PHONY : src/monkey.cc.o

src/monkey.i: src/monkey.cc.i
.PHONY : src/monkey.i

# target to preprocess a source file
src/monkey.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monkey.dir/build.make CMakeFiles/monkey.dir/src/monkey.cc.i
.PHONY : src/monkey.cc.i

src/monkey.s: src/monkey.cc.s
.PHONY : src/monkey.s

# target to generate assembly for a file
src/monkey.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monkey.dir/build.make CMakeFiles/monkey.dir/src/monkey.cc.s
.PHONY : src/monkey.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... doc"
	@echo "... examples"
	@echo "... travis_doc"
	@echo "... archivertest"
	@echo "... capitalize"
	@echo "... condense"
	@echo "... filterkey"
	@echo "... filterkeydom"
	@echo "... jsonx"
	@echo "... lookaheadparser"
	@echo "... messagereader"
	@echo "... monkey"
	@echo "... parsebyparts"
	@echo "... pretty"
	@echo "... prettyauto"
	@echo "... schemavalidator"
	@echo "... serialize"
	@echo "... simpledom"
	@echo "... simplepullreader"
	@echo "... simplereader"
	@echo "... simplewriter"
	@echo "... sortkeys"
	@echo "... tutorial"
	@echo "... src/monkey.o"
	@echo "... src/monkey.i"
	@echo "... src/monkey.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

